select
    "Number" as pokedex_id,
    "Name" as name,
    "Type 1" as type1,
    "Type 2" as type2,
    "HP" as hp,
    "Att" as attack,
    "Def" as defense,
    "Spa" as sp_attack,
    "Spd" as sp_defense,
    "Spe" as speed,
    "BST" as bst,
    "Mean" as mean,
    "Standard Deviation" as std,
    concat('Gen. ', cast("Generation" as varchar)) as generation,
    "Legendary" as legendary,
    "Against Normal" as ag_normal,
    "Against Fire" as ag_fire,
    "Against Water" as ag_water,
    "Against Electric" as ag_electric,
    "Against Grass" as ag_grass,
    "Against Ice" as ag_ice,
    "Against Fighting" as ag_fighting,
    "Against Poison" as ag_poison,
    "Against Ground" as ag_ground,
    "Against Flying" as ag_flying,
    "Against Psychic" as ag_psychic,
    "Against Bug" as ag_bug,
    "Against Rock" as ag_rock,
    "Against Ghost" as ag_ghost,
    "Against Dragon" as ag_dragon,
    "Against Dark" as ag_dark,
    "Against Steel" as ag_steel,
    "Against Fairy" as ag_fairy,
    "Height" as height,
    "Weight" as weight,
    "BMI" as bmi,
    replace(replace(replace("Abilities", '[', ''), ']', ''), '''', '') as abilities
from {{ source("src", "pokemons_tbl") }}
where "Number" is not null
