select
    "UniqeIdentifier" as pokemon_id,
    "No." as pokedex_number,
    initcap("Name") as name,
    "HP" as hp,
    "Att" as attack,
    "Def" as defense,
    "S.Att" as special_attack,
    "S.Def" as special_defense,
    "Spd" as speed,
    "Ph.Sweep" as physical_sweeper,
    "Sp.Sweep" as special_sweeper,
    "Wall" as wall,
    "Ph.Tank" as physical_tank,
    "Sp.Tank" as special_tank,
    initcap("PrimaryType") as type1,
    initcap(nullif(trim("SecondaryType"), '')) as type2,
    initcap("Ability") as ability,
    "Ability Gen" as ability_gen,
    initcap("Ability Category") as ability_category,
    "Activation Requirement" as activation_requirement,
    "Gen" as generation,
    concat('Gen. ', "Gen") as generation_desc,
    "Male%" as male_percentage,
    "Female%" as female_percentage,
    "against_Normal" as against_normal,
    "against_Fire" as against_fire,
    "against_Water" as against_water,
    "against_Electric" as against_electric,
    "against_Grass" as against_grass,
    "against_Ice" as against_ice,
    "against_Fight" as against_fight,
    "against_Poison" as against_poison,
    "against_Ground" as against_ground,
    "against_Flying" as against_flying,
    "against_Psychic" as against_psychic,
    "against_Bug" as against_bug,
    "against_Rock" as against_rock,
    "against_Ghost" as against_ghost,
    "against_Dragon" as against_dragon,
    "against_Dark" as against_dark,
    "against_Steel" as against_steel,
    "against_Fairy" as against_fairy,
    "Height (m)" as height,
    "Weight (kg)" as weight,
    "Capture Rate" as capture_rate,
    "Base Happiness" as base_happiness,
    "Base Egg Steps" as base_egg_steps,
    "Experience Growth" as experience_growth,
    "mega_evolution" as mega_evolution,
    "overall_legendary" as overall_legendary,
    "final_stage" as final_stage,
    "regional_form" as regional_form
from {{ source("src", "pokemons_2_tbl") }}
where "No." is not null
