
version: 2

sources:
  - name: src
    tables:
      - name: pokemons_tbl
        description: "A starter dbt model"
        columns:
          - name: Number
            description: "The primary key for this table"
            data_tests:
              - unique
              - not_null
  
